name: CI (Dockerized)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: django_db
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U django_user -d django_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-django-app/app ./project/app

      - name: Run migrations inside Docker
        run: docker run --rm --network="host" my-django-app python manage.py migrate

      - name: Run tests inside Docker
        run: docker run --rm --network="host" my-django-app python manage.py test
